language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly

before_script:
  - rustup update
  - rustup component add clippy-preview

script:
  - cargo clippy
  - cargo test

before_deploy:
  - cargo doc
  - cargo package
  
deploy:
  provider: releases
  api-key:
    secure:
  skip_cleanup: true
  on:
    tags: true
    branch: solana-master
    condition: "$TRAVIS_RUST_VERSION = stable"

after_deploy:
  - cargo publish --token "$CRATES_IO_TOKEN"
