[project]

# Project metadata
name = "rbpf"
version = "0.0.3"
authors = ["Quentin Monnet <quentin.monnet@6wind.com>"]

# Additional metadata for packaging
description = "Virtual machine and JIT compiler for eBPF programs"
repository = "https://github.com/qmonnet/rbpf"
readme = "README.md"
keywords = ["BPF", "eBPF", "interpreter", "JIT", "filtering"]
license = "Apache-2.0/MIT"

# Packaging directives
include = [
    "src/**",
    "examples/**",
    "tests/**",
    "bench/**",
    "LICENSE*",
    "Cargo.toml",
]

[dependencies]

combine = "2.1.1"
libc = "0.2.0"

[dev-dependencies]

byteorder = "0.5.3"
elf = "0.0.10"
json = "0.11.4"
